rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - jruby

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
install:
  - "bundle install --jobs=3 --retry=3"
